### ISSUE TITLE
heap-buffer-overflow in operations::read

### ISSUE THREAD

**Issue by riking** [carlosgaldino/fuse-rs#1]
https://asan.saethlin.dev/ub?crate=fuse-rs&version=0.0.1

WRITE of size 12 when only 9 bytes are valid

```
test operations::tests::test_read ... =================================================================
==24555==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x5020000050d9 at pc 0x561e6a5ec594 bp 0x7f92d23f41f0 sp 0x7f92d23f39b0
WRITE of size 12 at 0x5020000050d9 thread T20
    #0 0x561e6a5ec593 in __asan_memcpy /rustc/llvm/src/llvm-project/compiler-rt/lib/asan/asan_interceptors_memintrinsics.cpp:63:3
    #1 0x561e6a646515 in core::intrinsics::copy_nonoverlapping::h8fc4f9181e1d7f7a /root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/intrinsics.rs:2690:9
    #2 0x561e6a646515 in fuse_rs::operations::read::h23f1afcc7b40607f /build/src/operations.rs:214:17
    #3 0x561e6a628d07 in fuse_rs::operations::tests::test_read::h9d53628f987fefee /build/src/operations.rs:909:24
    #4 0x561e6a627072 in fuse_rs::operations::tests::test_read::_$u7b$$u7b$closure$u7d$$u7d$::h252abd37507203dd /build/src/operations.rs:862:19
```
```
0x5020000050d9 is located 0 bytes after 9-byte region [0x5020000050d0,0x5020000050d9)
allocated by thread T20 here:
    #0 0x561e6a5ee815 in realloc /rustc/llvm/src/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:85:3
    #1 0x561e6ab734a4 in std::sys::unix::alloc::_$LT$impl$u20$core..alloc..global..GlobalAlloc$u20$for$u20$std..alloc..System$GT$::realloc::hb1c3821af9e6d8fa /root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/unix/alloc.rs:48:13
    #2 0x561e6aaf6b38 in __rdl_realloc /root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/alloc.rs:416:13
    #3 0x561e6aeb81ac in alloc::alloc::Global::grow_impl::h9003a9ff27a0b33e /root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/alloc.rs:213:31
    #4 0x561e6aeb89ee in _$LT$alloc..alloc..Global$u20$as$u20$core..alloc..Allocator$GT$::grow::h81e4f48c2b05fe2d /root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/alloc.rs:266:18
    #5 0x561e6aeb474a in alloc::raw_vec::RawVec$LT$T$C$A$GT$::grow_exact::h4028860116507766 /root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/raw_vec.rs:423:19
    #6 0x561e6aeb3653 in alloc::raw_vec::RawVec$LT$T$C$A$GT$::try_reserve_exact::h7ec0baff1c604b73 /root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/raw_vec.rs:342:50
    #7 0x561e6aeb3526 in alloc::raw_vec::RawVec$LT$T$C$A$GT$::reserve_exact::h7b35a2a2e2da5382 /root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/raw_vec.rs:333:24
    #8 0x561e6aec22a2 in alloc::ffi::c_str::CString::from_vec_unchecked::hacdb5d8eafbef68b /root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/ffi/c_str.rs:342:18
    #9 0x561e6a628bf7 in fuse_rs::operations::tests::test_read::h9d53628f987fefee /build/src/operations.rs:906:23
    #10 0x561e6a627072 in fuse_rs::operations::tests::test_read::_$u7b$$u7b$closure$u7d$$u7d$::h252abd37507203dd /build/src/operations.rs:862:19
```
```
SUMMARY: AddressSanitizer: heap-buffer-overflow /rustc/llvm/src/llvm-project/compiler-rt/lib/asan/asan_interceptors_memintrinsics.cpp:63:3 in __asan_memcpy
Shadow bytes around the buggy address:
  0x502000004e00: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x502000004e80: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x502000004f00: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x502000004f80: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x502000005000: fa fa fd fa fa fa fd fa fa fa fd fd fa fa fd fa
=>0x502000005080: fa fa fd fd fa fa fd fa fa fa 00[01]fa fa 00 00
  0x502000005100: fa fa fd fd fa fa fd fa fa fa fa fa fa fa fa fa
  0x502000005180: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x502000005200: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x502000005280: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x502000005300: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==24555==ABORTING
error: test failed, to rerun pass `--lib`
```

**Comment by carlosgaldino** [comment]
This project has been archived.
